ecommerce_project/ecommerce_project/urls.py
from debug_toolbar.toolbar import debug_toolbar_urls
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = (
    i18n_patterns(
        path("admin/", admin.site.urls),
        path("", include("store.urls", namespace="store")),
        path("order/", include("order.urls", namespace="order")),
        path("user/", include("user.urls", namespace="user")),
        prefix_default_language=False,
    )
    + debug_toolbar_urls()
)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

admin.site.site_header = "Admin Page"

ecommerce_project/order/urls.py
from django.urls import path
from django.views.generic import TemplateView

from .views import AddCartItem, CartView, DeleteCartItem, UpdateCartItem

app_name = "order"

urlpatterns = [
    path("cart/add/", AddCartItem.as_view(), name="add_item_to_cart"),
    path("cart/delete/<int:pk>", DeleteCartItem.as_view(), name="delete_item"),
    path("cart/update/<int:pk>", UpdateCartItem.as_view(), name="update_item"),
    path("cart/", CartView.as_view(), name="cart"),
    path(
        "checkout/",
        TemplateView.as_view(template_name="checkout.html"),
        name="checkout",
    ),
]

ecommerce_project/store/urls.py
from django.urls import path
from django.views.generic import TemplateView

from .views import CategoryView, IndexView, ProductView

app_name = "store"

urlpatterns = [
    path("", IndexView.as_view(), name="home"),
    path("product/<slug:slug>/", ProductView.as_view(), name="product_details"),
    path("category/<slug:slug>", CategoryView.as_view(), name="category_listing"),
    path("category/", CategoryView.as_view(), name="all_categories"),
    path(
        "contact/", TemplateView.as_view(template_name="contact.html"), name="contact"
    ),
]

ecommerce_project/user/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path

from .views import Login, SignUp

app_name = "user"

urlpatterns = [
    path("login/", Login.as_view(), name="login"),
    path("logout/", LogoutView.as_view(next_page="store:home"), name="logout"),
    path("register/", SignUp.as_view(), name="register"),
]

ecommerce_project/store/models.py
from autoslug import AutoSlugField
from django.core.validators import MinValueValidator
from django.db import models
from versatileimagefield.fields import VersatileImageField

from .managers import CategoryManager, ProductManager, ProductTagManager


class Category(models.Model):
    name = models.CharField(max_length=100)
    slug = AutoSlugField(populate_from="name", unique=True)
    description = models.TextField(blank=True)
    parent = models.ForeignKey(
        "self", related_name="+", null=True, on_delete=models.SET_NULL, blank=True
    )
    image = VersatileImageField(upload_to="categories/", null=True, blank=True)
    objects = CategoryManager()

    def __str__(self):
        return self.name


class ProductTag(models.Model):
    name = models.CharField(max_length=50)
    objects = ProductTagManager()


class Product(models.Model):
    name = models.CharField(max_length=100)
    slug = AutoSlugField(populate_from="name", unique=True)
    description = models.TextField(blank=True)
    image = VersatileImageField(upload_to="products/", null=True, blank=True)
    price = models.FloatField(validators=[MinValueValidator(0)])
    category = models.ManyToManyField(Category)
    quantity = models.IntegerField(validators=[MinValueValidator(0)])
    tag = models.ManyToManyField(ProductTag, related_name="tags")

    objects = ProductManager()

    def __str__(self):
        return self.name

ecommerce_project/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

    {% include 'partials/header.html' %}

    <body>

        {% include 'partials/header_body.html' %}

        {% block content %}{% endblock content %}

        <!-- Page End -->
        {% include 'partials/footer.html' %}

        {% include 'partials/copyright.html' %}

        <!-- Back to Top -->
        <a href="#" class="btn btn-primary border-3 border-primary rounded-circle back-to-top"><i class="fa fa-arrow-up"></i></a>

        {% include 'partials/js_libraries.html' %}

        <!-- Template Javascript -->
        <script src="{% static 'js/main.js' %}"></script>

    </body>
</html>

ecommerce_project/templates/cart.html
{% extends 'base.html' %}
{% load static i18n%}
{% block content %}

{% trans "Cart" as page_title %}

{% include 'partials/single_page_header.html' with title=page_title%}


<!-- Cart Page Start -->
<div class="container-fluid py-5">
    <div class="container py-5">
        <div class="table-responsive">
            <table class="table">
                <thead>
                  <tr>
                    <th scope="col">{% trans "Products" %}</th>
                    <th scope="col">{% trans "Name" %}</th>
                    <th scope="col">{% trans "Price" %}</th>
                    <th scope="col">{% trans "Quantity" %}</th>
                    <th scope="col">{% trans "Total" %}</th>
                    <th scope="col">{% trans "Handle" %}</th>
                  </tr>
                </thead>
                <tbody>
                    {% for i in items %}
                        {% include 'cart/cart_item.html' with item=i%}
                    {% endfor %}
                </tbody>
            </table>
        </div>

{#        {% include 'cart/cart_total.html' with cart=cart%}#}
    </div>
</div>

{% endblock content %}

ecommerce_project/templates/checkout.html
{% extends 'base.html' %}
{% load static i18n%}
{% block content %}

{% trans "Checkout" as page_title %}

{% include 'partials/single_page_header.html' with title=page_title%}

<!-- Checkout Page Start -->
<div class="container-fluid py-5">
    <div class="container py-5">
        <h1 class="mb-4">Billing details</h1>
        <form action="#">
            <div class="row g-5">
                <div class="col-md-12 col-lg-6 col-xl-7">
                    <div class="row">
                        <div class="col-md-12 col-lg-6">
                            <div class="form-item w-100">
                                <label class="form-label my-3">First Name<sup>*</sup></label>
                                <input type="text" class="form-control">
                            </div>
                        </div>
                        <div class="col-md-12 col-lg-6">
                            <div class="form-item w-100">
                                <label class="form-label my-3">Last Name<sup>*</sup></label>
                                <input type="text" class="form-control">
                            </div>
                        </div>
                    </div>
                    <div class="form-item">
                        <label class="form-label my-3">Address <sup>*</sup></label>
                        <input type="text" class="form-control" placeholder="House Number Street Name">
                    </div>
                    <div class="form-item">
                        <label class="form-label my-3">Town/City<sup>*</sup></label>
                        <input type="text" class="form-control">
                    </div>
                    <div class="form-item">
                        <label class="form-label my-3">Country<sup>*</sup></label>
                        <input type="text" class="form-control">
                    </div>
                    <div class="form-item">
                        <label class="form-label my-3">Postcode/Zip<sup>*</sup></label>
                        <input type="text" class="form-control">
                    </div>
                    <div class="form-item">
                        <label class="form-label my-3">Mobile<sup>*</sup></label>
                        <input type="tel" class="form-control">
                    </div>
                    <div class="form-item">
                        <label class="form-label my-3">Email Address<sup>*</sup></label>
                        <input type="email" class="form-control">
                    </div>
                </div>
                {% include 'checkout/table.html' %}
            </div>
        </form>
    </div>
</div>

{% endblock content %}

ecommerce_project/templates/contact.html
{% extends 'base.html' %}
{% load i18n %}
{% block content %}

{% trans "Contact" as page_title %}

{% include 'partials/single_page_header.html' with title=page_title%}

<!-- Contact Start -->
<div class="container-fluid contact py-5">
    <div class="container py-5">
        <div class="p-5 bg-light rounded">
            <div class="row g-4">
                <div class="col-12">
                    <div class="text-center mx-auto" style="max-width: 700px;">
                        <h1 class="text-primary">Get in touch</h1>
                        <p class="mb-4">The contact form is currently inactive. Get a functional and working contact form with Ajax & PHP in a few minutes. Just copy and paste the files, add a little code and you're done. <a href="https://htmlcodex.com/contact-form">Download Now</a>.</p>
                    </div>
                </div>
                <div class="col-lg-12">
                    <div class="h-100 rounded">
                        <iframe class="rounded w-100"
                        style="height: 400px;" src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d387191.33750346623!2d-73.97968099999999!3d40.6974881!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x89c24fa5d33f083b%3A0xc80b8f06e177fe62!2sNew%20York%2C%20NY%2C%20USA!5e0!3m2!1sen!2sbd!4v1694259649153!5m2!1sen!2sbd"
                        loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
                    </div>
                </div>
                <div class="col-lg-7">
                    <form action="" class="">
                        <input type="text" class="w-100 form-control border-0 py-3 mb-4" placeholder="Your Name">
                        <input type="email" class="w-100 form-control border-0 py-3 mb-4" placeholder="Enter Your Email">
                        <textarea class="w-100 form-control border-0 mb-4" rows="5" cols="10" placeholder="Your Message"></textarea>
                        <button class="w-100 btn form-control border-secondary py-3 bg-white text-primary " type="submit">Submit</button>
                    </form>
                </div>
                <div class="col-lg-5">
                    <div class="d-flex p-4 rounded mb-4 bg-white">
                        <i class="fas fa-map-marker-alt fa-2x text-primary me-4"></i>
                        <div>
                            <h4>Address</h4>
                            <p class="mb-2">123 Street New York.USA</p>
                        </div>
                    </div>
                    <div class="d-flex p-4 rounded mb-4 bg-white">
                        <i class="fas fa-envelope fa-2x text-primary me-4"></i>
                        <div>
                            <h4>Mail Us</h4>
                            <p class="mb-2">info@example.com</p>
                        </div>
                    </div>
                    <div class="d-flex p-4 rounded bg-white">
                        <i class="fa fa-phone-alt fa-2x text-primary me-4"></i>
                        <div>
                            <h4>Telephone</h4>
                            <p class="mb-2">(+012) 3456 7890</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock content %}

ecommerce_project/templates/index.html
{% extends 'base.html' %}
{% load static i18n%}
{% block content %}

{% include "index/hero.html" %}

<!-- Fruits Shop Start-->
<div class="container-fluid fruite py-5">
    <div class="container py-5">
        <div class="tab-class text-center">
            <div class="row g-4">
                <div class="col-lg-4 text-start">
                    <h1>{% trans "Our Organic Products" %}</h1>
                </div>
                <div class="col-lg-8 text-end">
                    <ul class="nav nav-pills d-inline-flex text-center mb-5">
                        <li class="nav-item">
                            <a class="d-flex m-2 py-2 bg-light rounded-pill active" data-bs-toggle="pill" href="#tab-0">
                                <span class="text-dark" style="width: 130px;">{% trans "All Products" %}</span>
                            </a>
                        </li>
                        {% for c in header_categories %}
                            <li class="nav-item">
                                <a class="d-flex py-2 m-2 bg-light rounded-pill" data-bs-toggle="pill" href="#tab-{{ c.id }}">
                                    <span class="text-dark" style="width: 130px;">{{ c.name }}</span>
                                </a>
                            </li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
            <div class="tab-content">
                <div id="tab-0" class="tab-pane fade show p-0 active">
                    <div class="row g-4">
                        <div class="col-lg-12">
                            <div class="row g-4">
                                {% for p in products %}
                                <div class="col-md-6 col-lg-4 col-xl-3">
                                    {% include 'index/product.html' with product=p %}
                                </div>
                                {% endfor %}
                            </div>
                        </div>
                    </div>
                </div>

                {% for c in categories %}
                <div id="tab-{{ c.id }}" class="tab-pane fade show p-0">
                    <div class="row g-4">
                        <div class="col-lg-12">
                            <div class="row g-4">
                                {% for p in c.product_set.all %}
                                <div class="col-md-6 col-lg-4 col-xl-3">
                                    {% include 'index/product.html' with product=p %}
                                </div>
                                {% endfor %}
                            </div>
                        </div>
                    </div>
                </div>
                {% endfor %}

            </div>
        </div>
    </div>
</div>
{% endblock content %}

ecommerce_project/templates/login.html
{% load static i18n%}
<!DOCTYPE html>
<html lang="en">

    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>{% trans "Login" %}</title>
        <link rel="stylesheet" href="{% static 'css/auth.css' %}">
    </head>

    {% include 'partials/header.html' %}

    <body>
        <div class="auth-container">

            <h1>{% trans "Login" %}</h1>
            <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <input type="hidden" name="next" value="{{ request.GET.next }}">
                <button type="submit">{% trans "Log in" %}</button>
            </form>
            <p>{% trans "Don't have an account?" %}
                <br>
               <a href="{% url 'user:register' %}?next={{ request.GET.next }}" class="sign-up-button">{% trans "Sign Up" %}</a>
            </p>

        </div>
    </body>
</html>

ecommerce_project/templates/register.html
{% load static i18n%}
<!DOCTYPE html>
<html lang="en">

    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>{% trans "Sign Up"%}</title>
        <link rel="stylesheet" href="{% static 'css/auth.css' %}">
    </head>

    {% include 'partials/header.html' %}

    <body>
        <div class="auth-container">
            <h1>{% trans "Sign Up"%}</h1>
            <form method="post">
                {% csrf_token %}
                {% for field in form %}
                    <div class="form-group">
                        <label>{{ field.label_tag }}</label>
                        {{ field }}

                        {% if field.errors %}
                            <ul class="error">
                                {% for error in field.errors %}
                                    <li>{{ error }}</li>
                                {% endfor %}
                            </ul>
                        {% endif %}
                    </div>
                {% endfor %}
                <input type="hidden" name="next" value="{{ request.GET.next }}">

                <button type="submit">{% trans "Register" %}</button>
            </form>
        </div>
    </body>
</html>

ecommerce_project/templates/shop-detail.html
{% extends 'base.html' %}
{% load static i18n%}
{% block content %}

{% trans "Shop Detail" as shop_detail_title %}
{% include 'partials/single_page_header.html' with title=shop_detail_title %}

<!-- Single Product Start -->
<div class="container-fluid py-5 mt-5">
    <div class="container py-5">
        <div class="row g-4 mb-5">
            <div class="col-lg-8 col-xl-9">
                <div class="row g-4">
                    <div class="col-lg-6">
                        <div class="border rounded">
                            <a href="#">
                                <img src="{{ product.image.url }}" class="img-fluid rounded" alt="Image">
                            </a>
                        </div>
                    </div>
                    <div class="col-lg-6">
                        <h4 class="fw-bold mb-3">{{ product.name }}</h4>
                        <p class="mb-3">{% trans "Category" %}:
                            {% for c in product.category.all %}
                            {{ c.name }}{% if not forloop.last %}, {% endif %}
                            {% endfor %}
                        </p>
                        <p class="mb-3">{% trans "Tag" %}:
                            {% for t in product.tag.all %}
                                {{ t.name }}{% if not forloop.last %}, {% endif %}
                            {% endfor %}
                        </p>
                        <h5 class="fw-bold mb-3">{{ product.price }} $</h5>
                        {% if product.description != None %}
                            <p class="mb-4">{{ product.description }}</p>
                        {% endif %}
                        {% if product.quantity != 0 %}
                            <form action="{% url 'order:add_item_to_cart' %}" method="post" class="d-inline">
                                {% csrf_token %}
                                <div class="input-group quantity mb-5" style="width: 100px;">
                                    <div class="input-group-btn">
                                        <button type="button" class="btn btn-sm btn-minus rounded-circle bg-light border" >
                                            <i class="fa fa-minus"></i>
                                        </button>
                                    </div>
                                    <input type="text" name="quantity" class="form-control form-control-sm text-center border-0" value="1">
                                    <div class="input-group-btn">
                                        <button type="button" class="btn btn-sm btn-plus rounded-circle bg-light border">
                                            <i class="fa fa-plus"></i>
                                        </button>
                                    </div>
                                </div>
                                <input type="hidden" name="product_id" value="{{ product.id }}">
                                <button type="submit" class="btn border border-secondary rounded-pill px-3 text-primary">
                                    <i class="fa fa-shopping-bag me-2 text-primary"></i> {% trans "Add to cart" %}
                                </button>
                            </form>
                        {% else %}
                            <p>{% trans "Out of stock" %}</p>
                        {% endif %}
                    </div>
                </div>
            </div>
            <div class="col-lg-4 col-xl-3">
                <div class="row g-4 fruite">
                    <div class="col-lg-12">
                        <!-- Search -->
                        <form method="GET" action="{% url 'store:all_categories' %}">
                            <div class="input-group w-100 mx-auto d-flex mb-4">
                                <input type="search" name="filter_name" class="form-control p-3" placeholder={% trans "search" %} aria-describedby="search-icon-1">
                                <button type="submit" id="search-icon-1" class="input-group-text p-3">
                                    <i class="fa fa-search"></i>
                                </button>
                            </div>
                        </form>
                        <!-- Categories -->
                        <div class="mb-4">
                            <div class="mb-3">
                                <h4>{% trans "Categories" %}</h4>
                                <ul class="list-unstyled fruite-categorie">
                                    {% for c in header_categories %}
                                        <li>
                                            <div class="d-flex justify-content-between fruite-name">
                                                <a href="{% url 'store:category_listing' c.slug %}"><i class="fas fa-apple-alt me-2"></i>{{ c.name }}</a>
                                                <span></span>
                                            </div>
                                        </li>
                                    {% endfor %}
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <!--Related products -->
        <h1 class="fw-bold mb-0">{% trans "Related products" %}</h1>
        <div class="vesitable">
            <div class="owl-carousel vegetable-carousel justify-content-center">
                {% for p in related_products %}
                    <div class="border border-primary rounded position-relative vesitable-item">
                        <div class="vesitable-img">
                            <a href="{% url 'store:product_details' p.slug %}">
                                <img src="{{ p.image.crop.306x214 }}" class="img-fluid w-100 rounded-top" alt="">
                            </a>
                        </div>
                        {% if p.first_tag != None %}
                        <div class="text-white bg-primary px-3 py-1 rounded position-absolute" style="top: 10px; right: 10px;">
                            {{ p.first_tag.name }}</div>
                        {% endif %}
                        <div class="p-4 pb-0 rounded-bottom">
                            <h4>{{ p.name }}</h4>
                            <p>{{ p.description }}</p>
                            <div class="d-flex justify-content-between flex-lg-wrap">
                                <p class="text-dark fs-5 fw-bold">${{ p.price }}</p>
                                <form action="{% url 'order:add_item_to_cart' %}" method="post" class="d-inline">
                                    {% csrf_token %}
                                    <input type="hidden" name="product_id" value="{{ product.id }}">
                                    <button type="submit" class="btn border border-secondary rounded-pill px-3 text-primary">
                                        <i class="fa fa-shopping-bag me-2 text-primary"></i> {% trans "Add to cart" %}
                                    </button>
                                </form>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
</div>

{% endblock content %}

ecommerce_project/templates/shop.html
{% extends 'base.html' %}
{% load static i18n%}
{% block content %}

{% trans "Shop" as page_title %}

{% include 'partials/single_page_header.html' with title=page_title %}

{% include 'partials/catalog.html' %}

{% endblock content %}