ecommerce_project/ecommerce_project/urls.py
from debug_toolbar.toolbar import debug_toolbar_urls
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = (
    i18n_patterns(
        path("admin/", admin.site.urls),
        path("", include("store.urls", namespace="store")),
        path("order/", include("order.urls", namespace="order")),
        path("user/", include("user.urls", namespace="user")),
        prefix_default_language=False,
    )
    + debug_toolbar_urls()
)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

admin.site.site_header = "Admin Page"

ecommerce_project/order/urls.py
from django.urls import path
from django.views.generic import TemplateView

from .views import AddCartItem, CartView, DeleteCartItem, UpdateCartItem

app_name = "order"

urlpatterns = [
    path("cart/add/", AddCartItem.as_view(), name="add_item_to_cart"),
    path("cart/delete/<int:pk>", DeleteCartItem.as_view(), name="delete_item"),
    path("cart/update/<int:pk>", UpdateCartItem.as_view(), name="update_item"),
    path("cart/", CartView.as_view(), name="cart"),
    path(
        "checkout/",
        TemplateView.as_view(template_name="checkout.html"),
        name="checkout",
    ),
]

ecommerce_project/user/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path

from .views import Login, SignUp

app_name = "user"

urlpatterns = [
    path("login/", Login.as_view(), name="login"),
    path("logout/", LogoutView.as_view(next_page="store:home"), name="logout"),
    path("register/", SignUp.as_view(), name="register"),
]

ecommerce_project/templates/cart/cart_item.html
{% load static %}
<tr>
    <th scope="row">
        <div class="d-flex align-items-center">
            <img src="{{ item.product.image.url}}" class="img-fluid me-5 rounded-circle" style="width: 80px; height: 80px;" alt="">
        </div>
    </th>
    <td>
        <p class="mb-0 mt-4">{{item.product.name}}</p>
    </td>
    <td>
        <p class="mb-0 mt-4">{{ item.product.price }}$</p>
    </td>
    <td>
        <form action="{% url 'order:update_item' item.id %}" method="post">
        {% csrf_token %}
        <div class="input-group quantity mt-4" style="width: 100px;">
            <div class="input-group-btn">
                <button type="submit" name="dec" class="btn btn-sm btn-minus rounded-circle bg-light border" >
                    <i class="fa fa-minus"></i>
                </button>
            </div>
            <input type="text" class="form-control form-control-sm text-center border-0" value="{{ item.quantity }}"  max="{{ item.product.quantity }}" >
            <div class="input-group-btn">
                <button type="submit" name="inc" class="btn btn-sm btn-plus rounded-circle bg-light border">
                    <i class="fa fa-plus"></i>
                </button>
            </div>
        </div>
        </form>
    </td>
    <td>
        <p class="mb-0 mt-4">{{ item.total }}$</p>
    </td>

    <td>
        <form action="{% url 'order:delete_item' item.id %}" method="post">
            {% csrf_token %}
            <input type="hidden" name="delete_item_id" value="{{ item.id }}">
            <button class="btn btn-md rounded-circle bg-light border mt-4" >
                <i class="fa fa-times text-danger"></i>
            </button>
        </form>
    </td>
</tr>

ecommerce_project/templates/cart/cart_total.html
<div class="row g-4 justify-content-end">
    <div class="col-8"></div>
    <div class="col-sm-8 col-md-7 col-lg-6 col-xl-4">
        <div class="bg-light rounded">
            <div class="p-4">
                <h1 class="display-6 mb-4">Cart <span class="fw-normal">Total</span></h1>
                <div class="d-flex justify-content-between mb-4">
                    <h5 class="mb-0 me-4">Subtotal:</h5>
                    <p class="mb-0">$96.00</p>
                </div>
                <div class="d-flex justify-content-between">
                    <h5 class="mb-0 me-4">Shipping</h5>
                    <div class="">
                        <p class="mb-0">Flat rate: $3.00</p>
                    </div>
                </div>
            </div>
            <div class="py-4 mb-4 border-top border-bottom d-flex justify-content-between">
                <h5 class="mb-0 ps-4 me-4">Total</h5>
                <p class="mb-0 pe-4">$99.00</p>
            </div>
            <button class="btn border-secondary rounded-pill px-4 py-3 text-primary text-uppercase mb-4 ms-4" type="button" onclick="window.location.href='{% url 'order:checkout' %}'">Proceed Checkout</button>
        </div>
    </div>
</div>