ecommerce_project/ecommerce_project/urls.py
from debug_toolbar.toolbar import debug_toolbar_urls
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = (
    i18n_patterns(
        path("admin/", admin.site.urls),
        path("", include("store.urls", namespace="store")),
        path("order/", include("order.urls", namespace="order")),
        path("user/", include("user.urls", namespace="user")),
        prefix_default_language=False,
    )
    + debug_toolbar_urls()
)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

admin.site.site_header = "Admin Page"

ecommerce_project/order/urls.py
from django.urls import path
from django.views.generic import TemplateView

from .views import AddCartItem, CartView, DeleteCartItem, UpdateCartItem

app_name = "order"

urlpatterns = [
    path("cart/add/", AddCartItem.as_view(), name="add_item_to_cart"),
    path("cart/delete/<int:pk>", DeleteCartItem.as_view(), name="delete_item"),
    path("cart/update/<int:pk>", UpdateCartItem.as_view(), name="update_item"),
    path("cart/", CartView.as_view(), name="cart"),
    path(
        "checkout/",
        TemplateView.as_view(template_name="checkout.html"),
        name="checkout",
    ),
]

ecommerce_project/store/urls.py
from django.urls import path
from django.views.generic import TemplateView

from .views import CategoryView, IndexView, ProductView

app_name = "store"

urlpatterns = [
    path("", IndexView.as_view(), name="home"),
    path("product/<slug:slug>/", ProductView.as_view(), name="product_details"),
    path("category/<slug:slug>", CategoryView.as_view(), name="category_listing"),
    path("category/", CategoryView.as_view(), name="all_categories"),
    path(
        "contact/", TemplateView.as_view(template_name="contact.html"), name="contact"
    ),
]

ecommerce_project/user/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path

from .views import Login, SignUp

app_name = "user"

urlpatterns = [
    path("login/", Login.as_view(), name="login"),
    path("logout/", LogoutView.as_view(next_page="store:home"), name="logout"),
    path("register/", SignUp.as_view(), name="register"),
]

ecommerce_project/templates/partials/catalog.html
{% load static i18n %}

<!-- Fruits Shop Start-->
<div class="container-fluid fruite py-5">
    <div class="container py-5">
        <h1 class="mb-4">{% trans "Organic products shop" %}</h1>
        <div class="row g-4">
            <div class="col-lg-12">
                <div class="row g-4">
                    <div class="col-xl-3">

                        <!-- Search -->
                        <form method="GET" action="{% url 'store:all_categories' %}">
                            <div class="input-group w-100 mx-auto d-flex">
                                <input type="search" name="filter_name" class="form-control p-3" placeholder={% trans "search" %} aria-describedby="search-icon-1">
                                <button type="submit" id="search-icon-1" class="input-group-text p-3">
                                    <i class="fa fa-search"></i>
                                </button>
                            </div>
                        </form>
                    </div>
                    <div class="col-6"></div>
                    <div class="col-xl-3">
                        <div class="bg-light ps-3 py-3 rounded d-flex justify-content-between mb-4">
                            <label for="fruits">{% trans "Sorting" %}:</label>
                            <select id="fruits" name="fruitlist" class="border-0 form-select-sm bg-light me-3" form="fruitform">
                                <option value="">{% trans "Nothing" %}</option>
                                <option value="price_asc">{% trans "Price ascending" %}</option>
                                <option value="price_desc">{% trans "Price descending" %}</option>
                            </select>
                        </div>
                    </div>
                </div>

                <div class="row g-4">
                    <div class="col-lg-3">
                        <div class="row g-4">

                            <!-- Subcategories -->
                            <div class="col-lg-12">
                                <div class="mb-3">
                                    {% if subcategories %}
                                    <h4>{% trans "Categories" %}</h4>
                                    <ul class="list-unstyled fruite-categorie">
                                        {% for c in subcategories %}
                                            <li>
                                                <div class="d-flex justify-content-between fruite-name">
                                                    <a href="{% url 'store:category_listing' c.slug %}"><i class="fas fa-apple-alt me-2"></i>{{ c.name }}</a>
                                                    <span></span>
                                                </div>
                                            </li>
                                        {% endfor %}
                                    </ul>
                                    {% endif %}
                                </div>
                            </div>

                            <div class="col-lg-12">
                                <!-- Price Filter -->
                                {% if current_category %}
                                  <form method="GET" action="{% url 'store:category_listing' current_category %}">
                                {% else %}
                                  <form method="GET" action="{% url 'store:all_categories' %}">
                                {% endif %}
                                    <div class="mb-3">
                                        <h4 class="mb-2">{% trans "Price" %}</h4>
                                        <input type="range" class="form-range w-100" id="rangeInput" name="filter_price" min="0" max="30" value="0" oninput="amount.value=rangeInput.value">
                                        <output id="amount" name="amount" for="rangeInput">0</output>
                                    </div>

                                    <!-- Tags Filter -->
                                    <div class="mb-3">
                                        <h4>{% trans "Tags" %}</h4>
                                        {% for tag in tags %}
                                            <div class="mb-2">
                                                <input type="radio" name="filter_tag" class="me-2" id="tag_{{ tag.id }}" value="{{ tag.name }}">
                                                <label for="tag_{{ tag.id }}"> {{ tag.name }}</label>
                                            </div>
                                        {% endfor %}
                                    </div>

                                    <!-- Submit Button -->
                                    <button type="submit" class="btn btn-primary">{% trans "Filter" %}</button>
                                </form>
                            </div>
                        </div>
                    </div>


                    <div class="col-lg-9">
                    <div class="row">
                        {% for p in page_obj %}
                            <div class="col-lg-4 col-md-6 col-sm-12 mb-4">
                                {% include 'index/product.html' with product=p %}
                            </div>
                        {% endfor %}

                        <!-- Pagination -->
                        <div class="pagination d-flex justify-content-center mt-5">
                            {% if page_obj.has_previous %}
                                <a href="?page={{ page_obj.previous_page_number }}" class="rounded">&laquo;</a>
                            {% endif %}
                            {% for page_num in get_elided_page_range %}
                                {% if page_num == '…' %}
                                    <a href="javascript:void(0)" class="rounded">...</a>
                                {% else %}
                                    <a href="?page={{ page_num }}" class="{% if page_num == page_obj.number %}active{% endif %} rounded">{{ page_num }}</a>
                                {% endif %}
                            {% endfor %}
                            {% if page_obj.has_next %}
                                <a href="?page={{ page_obj.next_page_number }}" class="rounded">&raquo;</a>
                            {% endif %}
                        </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

ecommerce_project/templates/partials/copyright.html
<!-- Copyright Start -->
<div class="container-fluid copyright bg-dark py-4">
    <div class="container">
        <div class="row">
            <div class="col-md-6 text-center text-md-start mb-3 mb-md-0">
                <span class="text-light"><a href="#"><i class="fas fa-copyright text-light me-2"></i>Your Site Name</a>, All right reserved.</span>
            </div>
            <div class="col-md-6 my-auto text-center text-md-end text-white">
                <!--/*** This template is free as long as you keep the below author’s credit link/attribution link/backlink. ***/-->
                <!--/*** If you'd like to use the template without the below author’s credit link/attribution link/backlink, ***/-->
                <!--/*** you can purchase the Credit Removal License from "https://htmlcodex.com/credit-removal". ***/-->
                Designed By <a class="border-bottom" href="https://htmlcodex.com">HTML Codex</a> Distributed By <a class="border-bottom" href="https://themewagon.com">ThemeWagon</a>
            </div>
        </div>
    </div>
</div>
<!-- Copyright End -->

ecommerce_project/templates/partials/features.html
<!-- Featurs Section Start -->
    <div class="container-fluid featurs py-5">
        <div class="container py-5">
            <div class="row g-4">
                <div class="col-md-6 col-lg-3">
                    <div class="featurs-item text-center rounded bg-light p-4">
                        <div class="featurs-icon btn-square rounded-circle bg-secondary mb-5 mx-auto">
                            <i class="fas fa-car-side fa-3x text-white"></i>
                        </div>
                        <div class="featurs-content text-center">
                            <h5>Free Shipping</h5>
                            <p class="mb-0">Free on order over $300</p>
                        </div>
                    </div>
                </div>
                <div class="col-md-6 col-lg-3">
                    <div class="featurs-item text-center rounded bg-light p-4">
                        <div class="featurs-icon btn-square rounded-circle bg-secondary mb-5 mx-auto">
                            <i class="fas fa-user-shield fa-3x text-white"></i>
                        </div>
                        <div class="featurs-content text-center">
                            <h5>Security Payment</h5>
                            <p class="mb-0">100% security payment</p>
                        </div>
                    </div>
                </div>
                <div class="col-md-6 col-lg-3">
                    <div class="featurs-item text-center rounded bg-light p-4">
                        <div class="featurs-icon btn-square rounded-circle bg-secondary mb-5 mx-auto">
                            <i class="fas fa-exchange-alt fa-3x text-white"></i>
                        </div>
                        <div class="featurs-content text-center">
                            <h5>30 Day Return</h5>
                            <p class="mb-0">30 day money guarantee</p>
                        </div>
                    </div>
                </div>
                <div class="col-md-6 col-lg-3">
                    <div class="featurs-item text-center rounded bg-light p-4">
                        <div class="featurs-icon btn-square rounded-circle bg-secondary mb-5 mx-auto">
                            <i class="fa fa-phone-alt fa-3x text-white"></i>
                        </div>
                        <div class="featurs-content text-center">
                            <h5>24/7 Support</h5>
                            <p class="mb-0">Support every time fast</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Featurs Section End -->

ecommerce_project/templates/partials/footer.html
{% load static i18n%}
<!-- Footer Start -->
<div class="container-fluid bg-dark text-white-50 footer pt-5 mt-5">
    <div class="container py-5">
        <div class="pb-4 mb-4" style="border-bottom: 1px solid rgba(226, 175, 24, 0.5) ;">
            <div class="row g-4">
                <div class="col-lg-3">
                    <a href="{% url 'store:home' %}">
                        <h1 class="text-primary mb-0">{% trans 'Fruitables' %}</h1>
                        <p class="text-secondary mb-0">{% trans "Fresh products" %}</p>
                    </a>
                </div>
                <div class="col-lg-6">
                    <div class="position-relative mx-auto">
                        <input class="form-control border-0 w-100 py-3 px-4 rounded-pill" type="number" placeholder="Your Email">
                        <button type="submit" class="btn btn-primary border-0 border-secondary py-3 px-4 position-absolute rounded-pill text-white" style="top: 0; right: 0;">Subscribe Now</button>
                    </div>
                </div>
                <div class="col-lg-3">
                    <div class="d-flex justify-content-end pt-3">
                        <a class="btn  btn-outline-secondary me-2 btn-md-square rounded-circle" href=""><i class="fab fa-twitter"></i></a>
                        <a class="btn btn-outline-secondary me-2 btn-md-square rounded-circle" href=""><i class="fab fa-facebook-f"></i></a>
                        <a class="btn btn-outline-secondary me-2 btn-md-square rounded-circle" href=""><i class="fab fa-youtube"></i></a>
                        <a class="btn btn-outline-secondary btn-md-square rounded-circle" href=""><i class="fab fa-linkedin-in"></i></a>
                    </div>
                </div>
            </div>
        </div>
        <div class="row g-5">
            <div class="col-lg-3 col-md-6">
                <div class="footer-item">
                    <h4 class="text-light mb-3">Why People Like us!</h4>
                    <p class="mb-4">typesetting, remaining essentially unchanged. It was
                        popularised in the 1960s with the like Aldus PageMaker including of Lorem Ipsum.</p>
                    <a href="" class="btn border-secondary py-2 px-4 rounded-pill text-primary">Read More</a>
                </div>
            </div>
            <div class="col-lg-3 col-md-6">
                <div class="d-flex flex-column text-start footer-item">
                    <h4 class="text-light mb-3">Shop Info</h4>
                    <a class="btn-link" href="">About Us</a>
                    <a class="btn-link" href="{% url 'store:contact' %}">Contact Us</a>
                    <a class="btn-link" href="">Privacy Policy</a>
                    <a class="btn-link" href="">Terms & Condition</a>
                    <a class="btn-link" href="">Return Policy</a>
                    <a class="btn-link" href="">FAQs & Help</a>
                </div>
            </div>
            <div class="col-lg-3 col-md-6">
                <div class="d-flex flex-column text-start footer-item">
                    <h4 class="text-light mb-3">Account</h4>
                    <a class="btn-link" href="">My Account</a>
                    <a class="btn-link" href="{% url 'store:all_categories' %}">Shop details</a>
                    <a class="btn-link" href="{% url 'order:cart' %}">Shopping Cart</a>
{#                    <a class="btn-link" href="">Wishlist</a>#}
{#                    <a class="btn-link" href="">Order History</a>#}
{#                    <a class="btn-link" href="">International Orders</a>#}
                </div>
            </div>
            <div class="col-lg-3 col-md-6">
                <div class="footer-item">
                    <h4 class="text-light mb-3">Contact</h4>
                    <p>Address: 1429 Netus Rd, NY 48247</p>
                    <p>Email: Example@gmail.com</p>
                    <p>Phone: +0123 4567 8910</p>
                    <p>Payment Accepted</p>
                    <img src="{% static 'img/payment.png' %}" class="img-fluid" alt="">
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Footer End -->

ecommerce_project/templates/partials/header.html
{% load static i18n%}
<head>

    <meta charset="utf-8">

    <title>{% trans "Fruitables" %}</title>

    <meta content="width=device-width, initial-scale=1.0" name="viewport">

    <meta content="" name="keywords">

    <meta content="" name="description">


    <!-- Google Web Fonts -->

    <link rel="preconnect" href="https://fonts.googleapis.com">

    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>

    <link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@400;600&family=Raleway:wght@600;800&display=swap" rel="stylesheet">



    <!-- Icon Font Stylesheet -->

    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.4/css/all.css"/>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet">



    <!-- Libraries Stylesheet -->

    <link href="{% static 'lib/lightbox/css/lightbox.min.css' %}" rel="stylesheet">

    <link href="{% static 'lib/owlcarousel/assets/owl.carousel.min.css' %}" rel="stylesheet">



    <!-- Customized Bootstrap Stylesheet -->

    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">



    <!-- Template Stylesheet -->

    <link href="{% static 'css/style.css' %}" rel="stylesheet">

 </head>

ecommerce_project/templates/partials/header_body.html
{% load static i18n %}

<!-- Spinner Start -->
<div id="spinner" class="show w-100 vh-100 bg-white position-fixed translate-middle top-50 start-50  d-flex align-items-center justify-content-center">

    <div class="spinner-grow text-primary" role="status"></div>

</div>

<!-- Spinner End -->

<!-- Navbar start -->

<div class="container-fluid fixed-top">

    <div class="container topbar bg-primary d-none d-lg-block">

        <div class="d-flex justify-content-between">

            <div class="top-info ps-2">

            </div>

            <div class="top-link pe-2">

            </div>

        </div>

    </div>

    <div class="container px-0">

        <nav class="navbar navbar-light bg-white navbar-expand-xl">

            <a href="{% url 'store:home' %}" class="navbar-brand"><h1 class="text-primary display-6">{% trans "Fruitables" %}</h1></a>

            <button class="navbar-toggler py-2 px-3" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse">

                <span class="fa fa-bars text-primary"></span>

            </button>
            <div class="collapse navbar-collapse bg-white" id="navbarCollapse">
                <div class="navbar-nav mx-auto">

                    <a href="{% url 'store:home' %}" class="nav-item nav-link">{% trans "Home" %}</a>

                    <a href="{% url 'store:all_categories' %}" class="nav-item nav-link">{% trans "Shop" %}</a>

                    <div class="nav-item dropdown">

                        <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown">{% trans "Category" %}</a>

                        <div class="dropdown-menu m-0 bg-secondary rounded-0">

                            {% for category in header_categories %}

                                <a href="{% url 'store:category_listing' slug=category.slug %}" class="dropdown-item">{{ category }}</a>

                            {% endfor %}

                        </div>

                    </div>

                    <a href="{% url 'store:contact' %}" class="nav-item nav-link">{% trans "Contact" %}</a>

                </div>
                <div class="d-flex m-3 me-0">

                    <button class="btn-search btn border border-secondary btn-md-square rounded-circle bg-white me-4" data-bs-toggle="modal" data-bs-target="#searchModal"><i class="fas fa-search text-primary"></i></button>

                    <a href="{% url 'order:cart' %}" class="position-relative me-4 my-auto">

                        <i class="fa fa-shopping-bag fa-2x"></i>

                        <span class="position-absolute bg-secondary rounded-circle d-flex align-items-center justify-content-center text-dark px-1" style="top: -5px; left: 15px; height: 20px; min-width: 20px;">{{ cart_items_quantity }}</span>

                    </a>

                    <a href="#" class="my-auto">
                        <i class="fas fa-user fa-2x"></i>
                    </a>

                    {% if request.user.is_authenticated %}
                        <a href="{% url 'user:logout' %}">
                            <img src="{% static 'img/logout.webp' %}" alt="Logout" width="40" height="40"/>
                        </a>
                    {% else %}
                        <a href="{% url 'user:login' %}">
                            <img src="{% static 'img/login.png' %}" alt="Login" width="40" height="40"/>
                        </a>
                    {% endif %}
                </div>

            </div>

        </nav>

    </div>

</div>

<!-- Navbar End -->





<!-- Modal Search Start -->
<form method="GET" action="{% url 'store:all_categories' %}">
<div class="modal fade" id="searchModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">

    <div class="modal-dialog modal-fullscreen">

        <div class="modal-content rounded-0">

            <div class="modal-header">

{#                <h5 class="modal-title" id="exampleModalLabel">Search by keyword</h5>#}

                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>

            </div>

            <div class="modal-body d-flex align-items-center">
                <div class="input-group w-75 mx-auto d-flex">
                        <input type="search" name="filter_name" class="form-control p-3" placeholder={% trans "search" %} aria-describedby="search-icon-1">
                        <span type="submit" id="search-icon-1" class="input-group-text p-3"><i class="fa fa-search"></i></span>
                </div>
            </div>
        </div>
    </div>
</div>
</form>
<!-- Modal Search End -->

ecommerce_project/templates/partials/js_libraries.html
{% load static %}

<!-- JavaScript Libraries -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.4/jquery.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"></script>
<script src="{% static 'lib/easing/easing.min.js' %}"></script>
<script src="{% static 'lib/waypoints/waypoints.min.js' %}"></script>
<script src="{% static 'lib/lightbox/js/lightbox.min.js' %}"></script>
<script src="{% static 'lib/owlcarousel/owl.carousel.min.js' %}"></script>

ecommerce_project/templates/partials/single_page_header.html
{% load i18n %}
<!-- Single Page Header start -->
<div class="container-fluid page-header py-5">
    <h1 class="text-center text-white display-6">{{title}}</h1>
    <ol class="breadcrumb justify-content-center mb-0">
        <li class="breadcrumb-item"><a href="{% url 'store:home' %}">{% trans "Home" %}</a></li>
{#        <li class="breadcrumb-item"><a href="#">Pages</a></li>#}
        <li class="breadcrumb-item active text-white">{{title}}</li>
    </ol>
</div>
<!-- Single Page Header End -->